apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wp
spec:
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30060
  selector:
    app: wp
    tier: frontend
  type: NodePort
 
